"""Dados de referência (subconjuntos usuais da APS)."""

# ── CID-10 (seleção frequente na atenção primária) ──
CID10 = [
    ("A09", "Diarreia e gastroenterite de origem infecciosa presumível"),
    ("B34.9", "Infecção viral não especificada"),
    ("E11.9", "Diabetes mellitus tipo 2 sem complicações"),
    ("E66.9", "Obesidade não especificada"),
    ("E78.5", "Hiperlipidemia não especificada"),
    ("F32.9", "Episódio depressivo não especificado"),
    ("F41.1", "Ansiedade generalizada"),
    ("G43.9", "Enxaqueca não especificada"),
    ("H10.9", "Conjuntivite não especificada"),
    ("H61.2", "Impactação de cerúmen"),
    ("H66.9", "Otite média não especificada"),
    ("H81.1", "Vertigem posicional paroxística benigna"),
    ("H93.1", "Zumbido (tinnitus)"),
    ("I10", "Hipertensão essencial (primária)"),
    ("J00", "Nasofaringite aguda (resfriado comum)"),
    ("J01.9", "Sinusite aguda não especificada"),
    ("J02.9", "Faringite aguda não especificada"),
    ("J03.9", "Amigdalite aguda não especificada"),
    ("J06.9", "Infecção aguda das vias aéreas superiores não especificada"),
    ("J11", "Influenza devida a vírus não identificado"),
    ("J20.9", "Bronquite aguda não especificada"),
    ("J30.4", "Rinite alérgica não especificada"),
    ("J32.9", "Sinusite crônica não especificada"),
    ("J34.2", "Desvio de septo nasal"),
    ("J35.1", "Hipertrofia das amígdalas"),
    ("J45.9", "Asma não especificada"),
    ("K21.9", "Doença de refluxo gastroesofágico sem esofagite"),
    ("K29.7", "Gastrite não especificada"),
    ("K59.0", "Constipação"),
    ("L20.9", "Dermatite atópica não especificada"),
    ("L23.9", "Dermatite alérgica de contato de causa não especificada"),
    ("M54.5", "Dor lombar baixa"),
    ("M79.1", "Mialgia"),
    ("N30.0", "Cistite aguda"),
    ("N39.0", "Infecção do trato urinário de localização não especificada"),
    ("O26.9", "Afecção relacionada à gravidez não especificada"),
    ("R05", "Tosse"),
    ("R07.4", "Dor torácica não especificada"),
    ("R10.4", "Outras dores abdominais e as não especificadas"),
    ("R42", "Tontura e instabilidade"),
    ("R50.9", "Febre não especificada"),
    ("R51", "Cefaleia"),
    ("R53", "Mal-estar e fadiga"),
    ("Z00.0", "Exame médico geral"),
    ("Z34.9", "Supervisão de gravidez normal não especificada"),
    ("Z71.3", "Aconselhamento e vigilância dietética"),
    ("Z76.0", "Emissão de receita de repetição"),
]

# ── CIAP-2 (Classificação Internacional de APS) ──
CIAP2 = [
    ("A03", "Febre"),
    ("A04", "Fraqueza / cansaço geral"),
    ("A77", "Doença viral não especificada"),
    ("A97", "Sem doença"),
    ("D01", "Dor abdominal generalizada / cólica"),
    ("D11", "Diarreia"),
    ("D84", "Doença do esôfago"),
    ("D87", "Alteração funcional do estômago"),
    ("H71", "Otite média aguda"),
    ("H81", "Vertigem / síndrome vestibular"),
    ("H29", "Zumbido / outros sintomas do ouvido"),
    ("K86", "Hipertensão sem complicações"),
    ("K87", "Hipertensão com complicações"),
    ("K25", "Medo de doença cardiovascular"),
    ("L03", "Sintoma / queixa da região lombar"),
    ("L18", "Dor muscular"),
    ("N01", "Cefaleia"),
    ("N17", "Vertigem / tontura"),
    ("P76", "Depressão"),
    ("P74", "Transtorno de ansiedade"),
    ("R05", "Tosse"),
    ("R74", "Infecção aguda das vias respiratórias superiores"),
    ("R09", "Sintoma / queixa nasal"),
    ("R75", "Sinusite aguda / crônica"),
    ("R76", "Amigdalite aguda"),
    ("R97", "Rinite alérgica"),
    ("R78", "Bronquite aguda / bronquiolite"),
    ("R96", "Asma"),
    ("S88", "Dermatite de contato / alérgica"),
    ("T90", "Diabetes não insulino-dependente"),
    ("T93", "Distúrbio do metabolismo dos lipídios"),
    ("U71", "Cistite / outra infecção urinária"),
    ("W78", "Gravidez"),
    ("A98", "Manutenção da saúde / medicina preventiva"),
    ("A85", "Efeito adverso de medicamento com dose correta"),
]

# ── Medicamentos (Relação Municipal / farmácia básica) ──
MEDICAMENTOS = [
    ("Amoxicilina 500 mg", "Amoxicilina", "cápsula"),
    ("Amoxicilina + Clavulanato 500/125 mg", "Amoxicilina/Clavulanato", "comprimido"),
    ("Azitromicina 500 mg", "Azitromicina", "comprimido"),
    ("Cefalexina 500 mg", "Cefalexina", "cápsula"),
    ("Dipirona 500 mg", "Dipirona sódica", "comprimido"),
    ("Dipirona gotas 500 mg/mL", "Dipirona sódica", "solução oral"),
    ("Paracetamol 500 mg", "Paracetamol", "comprimido"),
    ("Paracetamol gotas 200 mg/mL", "Paracetamol", "solução oral"),
    ("Ibuprofeno 600 mg", "Ibuprofeno", "comprimido"),
    ("Ibuprofeno 50 mg/mL", "Ibuprofeno", "suspensão oral"),
    ("Prednisolona 3 mg/mL", "Prednisolona", "solução oral"),
    ("Prednisona 20 mg", "Prednisona", "comprimido"),
    ("Dexametasona 4 mg", "Dexametasona", "comprimido"),
    ("Loratadina 10 mg", "Loratadina", "comprimido"),
    ("Dexclorfeniramina 2 mg", "Dexclorfeniramina", "comprimido"),
    ("Salbutamol spray 100 mcg", "Salbutamol", "aerossol"),
    ("Beclometasona spray 250 mcg", "Beclometasona", "aerossol"),
    ("Losartana 50 mg", "Losartana potássica", "comprimido"),
    ("Enalapril 10 mg", "Maleato de enalapril", "comprimido"),
    ("Hidroclorotiazida 25 mg", "Hidroclorotiazida", "comprimido"),
    ("Anlodipino 5 mg", "Besilato de anlodipino", "comprimido"),
    ("Atenolol 25 mg", "Atenolol", "comprimido"),
    ("Metformina 500 mg", "Cloridrato de metformina", "comprimido"),
    ("Metformina 850 mg", "Cloridrato de metformina", "comprimido"),
    ("Glibenclamida 5 mg", "Glibenclamida", "comprimido"),
    ("Insulina NPH 100 UI/mL", "Insulina humana NPH", "suspensão injetável"),
    ("Sinvastatina 20 mg", "Sinvastatina", "comprimido"),
    ("Omeprazol 20 mg", "Omeprazol", "cápsula"),
    ("Ranitidina 150 mg", "Ranitidina", "comprimido"),
    ("Sais de reidratação oral", "Sais para reidratação oral", "pó para solução"),
    ("Sulfato ferroso 40 mg Fe", "Sulfato ferroso", "comprimido"),
    ("Ácido fólico 5 mg", "Ácido fólico", "comprimido"),
    ("Metronidazol 250 mg", "Metronidazol", "comprimido"),
    ("Nitrofurantoína 100 mg", "Nitrofurantoína", "cápsula"),
    ("Fluoxetina 20 mg", "Cloridrato de fluoxetina", "cápsula"),
    ("Amitriptilina 25 mg", "Cloridrato de amitriptilina", "comprimido"),
    ("Ivermectina 6 mg", "Ivermectina", "comprimido"),
    ("Albendazol 400 mg", "Albendazol", "comprimido"),
]

# ── Exames (SIA/SUS mais pedidos na APS) ──
EXAMES = [
    ("Hemograma completo", "HMG"),
    ("Glicemia de jejum", "GJ"),
    ("Hemoglobina glicada", "HbA1c"),
    ("Colesterol total e frações", "Lipidograma"),
    ("Triglicerídeos", None),
    ("Ureia", None),
    ("Creatinina", None),
    ("TGO / AST", None),
    ("TGP / ALT", None),
    ("TSH", None),
    ("T4 livre", None),
    ("Ácido úrico", None),
    ("Sódio e potássio", "Eletrólitos"),
    ("Urina tipo I / EAS", "Urina rotina"),
    ("Urocultura com antibiograma", None),
    ("Parasitológico de fezes", "EPF"),
    ("Beta-HCG quantitativo", None),
    ("VDRL", None),
    ("Anti-HIV", None),
    ("HBsAg", None),
    ("Anti-HCV", None),
    ("Eletrocardiograma", "ECG"),
    ("Raio-X de tórax", "RX tórax"),
    ("Ultrassonografia abdominal total", "USG abdome"),
    ("Citopatológico de colo uterino", "Preventivo / Papanicolau"),
    ("Mamografia bilateral", None),
    # Otorrinolaringologia
    ("Audiometria tonal liminar", "Audiometria"),
    ("Audiometria vocal (IRF/IPRF)", None),
    ("Imitanciometria", "Timpanometria"),
    ("Emissões otoacústicas", "EOA"),
    ("Potencial evocado auditivo de tronco encefálico", "BERA / PEATE"),
    ("Videonistagmografia", "VNG — exame vestibular / equilíbrio"),
    ("Nasofibrolaringoscopia", "Nasofibroscopia"),
    ("Videoendoscopia nasal", "Endoscopia nasal"),
    ("Rinomanometria", None),
    ("Tomografia computadorizada dos seios da face", "TC de seios paranasais"),
    ("Raio-X de seios da face", "RX de cavum / seios paranasais"),
    ("Cultura de secreção de orofaringe", "Swab de garganta"),
]
